"""add entity resolution knowledge graph and workflows

Revision ID: 0e5304bea395
Revises: 509e10656dfd
Create Date: 2026-08-19 09:20:23.534604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5304bea395'
down_revision: Union[str, Sequence[str], None] = '509e10656dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_number')
    )
    op.create_index(op.f('ix_platform_features_id'), 'platform_features', ['id'], unique=False)
    op.create_table('agent_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tools_json', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_definitions_id'), 'agent_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_definitions_workspace_id'), 'agent_definitions', ['workspace_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    op.create_index(op.f('ix_ai_insights_insight_type'), 'ai_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_workspace_id'), 'ai_insights', ['workspace_id'], unique=False)
    op.create_table('platform_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('canonical_email', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_entities_entity_type'), 'platform_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_platform_entities_id'), 'platform_entities', ['id'], unique=False)
    op.create_index(op.f('ix_platform_entities_workspace_id'), 'platform_entities', ['workspace_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_enabled'), 'workflows', ['enabled'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_workspace_id'), 'workflows', ['workspace_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_id'), 'ai_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_workspace_id'), 'ai_feedback', ['workspace_id'], unique=False)
    op.create_table('connector_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=500), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_permissions_connector_id'), 'connector_permissions', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_permissions_id'), 'connector_permissions', ['id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['platform_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_alias'), 'entity_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_id'), 'entity_aliases', ['id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['platform_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['platform_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_id'), 'knowledge_edges', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_relationship_type'), 'knowledge_edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_source_entity_id'), 'knowledge_edges', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_target_entity_id'), 'knowledge_edges', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_workspace_id'), 'knowledge_edges', ['workspace_id'], unique=False)
    op.create_table('knowledge_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_versions_id'), 'knowledge_versions', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_versions_resource_id'), 'knowledge_versions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_knowledge_versions_resource_type'), 'knowledge_versions', ['resource_type'], unique=False)
    op.create_index(op.f('ix_knowledge_versions_workspace_id'), 'knowledge_versions', ['workspace_id'], unique=False)
    op.create_table('workspace_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('view_type', sa.String(length=50), nullable=False),
    sa.Column('configuration_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_views_id'), 'workspace_views', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_views_workspace_id'), 'workspace_views', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_views_workspace_id'), table_name='workspace_views')
    op.drop_index(op.f('ix_workspace_views_id'), table_name='workspace_views')
    op.drop_table('workspace_views')
    op.drop_index(op.f('ix_knowledge_versions_workspace_id'), table_name='knowledge_versions')
    op.drop_index(op.f('ix_knowledge_versions_resource_type'), table_name='knowledge_versions')
    op.drop_index(op.f('ix_knowledge_versions_resource_id'), table_name='knowledge_versions')
    op.drop_index(op.f('ix_knowledge_versions_id'), table_name='knowledge_versions')
    op.drop_table('knowledge_versions')
    op.drop_index(op.f('ix_knowledge_edges_workspace_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_target_entity_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_source_entity_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_relationship_type'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_entity_aliases_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_connector_permissions_id'), table_name='connector_permissions')
    op.drop_index(op.f('ix_connector_permissions_connector_id'), table_name='connector_permissions')
    op.drop_table('connector_permissions')
    op.drop_index(op.f('ix_ai_feedback_workspace_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_workflows_workspace_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_enabled'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_platform_entities_workspace_id'), table_name='platform_entities')
    op.drop_index(op.f('ix_platform_entities_id'), table_name='platform_entities')
    op.drop_index(op.f('ix_platform_entities_entity_type'), table_name='platform_entities')
    op.drop_table('platform_entities')
    op.drop_index(op.f('ix_ai_insights_workspace_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_insight_type'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_agent_definitions_workspace_id'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_id'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    op.drop_index(op.f('ix_platform_features_id'), table_name='platform_features')
    op.drop_table('platform_features')
    # ### end Alembic commands ###
