"""add meeting intelligence models

Revision ID: 46f7ea4d5ae5
Revises: bf229dc85b78
Create Date: 2026-08-17 09:26:57.717816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f7ea4d5ae5'
down_revision: Union[str, Sequence[str], None] = 'bf229dc85b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_type', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('meeting_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('speaker_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_decisions_id'), 'meeting_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_decisions_meeting_id'), 'meeting_decisions', ['meeting_id'], unique=False)
    op.create_table('meeting_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('follow_ups', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_summaries_id'), 'meeting_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_summaries_meeting_id'), 'meeting_summaries', ['meeting_id'], unique=True)
    op.create_table('meeting_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_action_items_assignee_user_id'), 'meeting_action_items', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_id'), 'meeting_action_items', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_meeting_id'), 'meeting_action_items', ['meeting_id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('speaker_label', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_participants_id'), 'meeting_participants', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_user_id'), 'meeting_participants', ['user_id'], unique=False)
    op.create_table('meeting_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=100), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('start_time_seconds', sa.Float(), nullable=True),
    sa.Column('end_time_seconds', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['meeting_participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_transcripts_id'), 'meeting_transcripts', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_transcripts_meeting_id'), 'meeting_transcripts', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_transcripts_participant_id'), 'meeting_transcripts', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_transcripts_participant_id'), table_name='meeting_transcripts')
    op.drop_index(op.f('ix_meeting_transcripts_meeting_id'), table_name='meeting_transcripts')
    op.drop_index(op.f('ix_meeting_transcripts_id'), table_name='meeting_transcripts')
    op.drop_table('meeting_transcripts')
    op.drop_index(op.f('ix_meeting_participants_user_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meeting_action_items_meeting_id'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_id'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_assignee_user_id'), table_name='meeting_action_items')
    op.drop_table('meeting_action_items')
    op.drop_index(op.f('ix_meeting_summaries_meeting_id'), table_name='meeting_summaries')
    op.drop_index(op.f('ix_meeting_summaries_id'), table_name='meeting_summaries')
    op.drop_table('meeting_summaries')
    op.drop_index(op.f('ix_meeting_decisions_meeting_id'), table_name='meeting_decisions')
    op.drop_index(op.f('ix_meeting_decisions_id'), table_name='meeting_decisions')
    op.drop_table('meeting_decisions')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
