"""add document permissions

Revision ID: 599aa33319b0
Revises: b428abed0544
Create Date: 2026-08-16 14:54:56.995720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599aa33319b0'
down_revision: Union[str, Sequence[str], None] = 'b428abed0544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=50), server_default='read', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_document_permission_user')
    )
    op.create_index(op.f('ix_document_permissions_document_id'), 'document_permissions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_permissions_user_id'), 'document_permissions', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_column('documents', 'owner_id')
    op.drop_index(op.f('ix_document_permissions_user_id'), table_name='document_permissions')
    op.drop_index(op.f('ix_document_permissions_document_id'), table_name='document_permissions')
    op.drop_table('document_permissions')
    # ### end Alembic commands ###
