"""add user workspace relationship

Revision ID: 5da40b20091d
Revises: 8a10d032eb0c
Create Date: 2026-08-14 11:08:31.078925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da40b20091d'
down_revision: Union[str, Sequence[str], None] = '8a10d032eb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'users', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_column('users', 'workspace_id')
    # ### end Alembic commands ###
