"""add external permission synchronization

Revision ID: bf229dc85b78
Revises: 63fe52ee13dd
Create Date: 2026-08-17 09:09:14.150722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf229dc85b78'
down_revision: Union[str, Sequence[str], None] = '63fe52ee13dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_name', sa.String(length=100), nullable=False),
    sa.Column('external_resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_name', sa.String(length=500), nullable=False),
    sa.Column('resource_url', sa.Text(), nullable=True),
    sa.Column('parent_resource_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_name', 'external_resource_id', name='uq_external_resource_connector_resource')
    )
    op.create_index(op.f('ix_external_resources_connector_name'), 'external_resources', ['connector_name'], unique=False)
    op.create_index(op.f('ix_external_resources_external_resource_id'), 'external_resources', ['external_resource_id'], unique=False)
    op.create_index(op.f('ix_external_resources_id'), 'external_resources', ['id'], unique=False)
    op.create_table('external_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connector_name', sa.String(length=100), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('external_username', sa.String(length=255), nullable=True),
    sa.Column('external_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_name', 'external_user_id', name='uq_external_identity_connector_user')
    )
    op.create_index(op.f('ix_external_identities_connector_name'), 'external_identities', ['connector_name'], unique=False)
    op.create_index(op.f('ix_external_identities_external_user_id'), 'external_identities', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_external_identities_id'), 'external_identities', ['id'], unique=False)
    op.create_index(op.f('ix_external_identities_user_id'), 'external_identities', ['user_id'], unique=False)
    op.create_table('external_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_identity_id', sa.Integer(), nullable=False),
    sa.Column('external_resource_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('inherited', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['external_identity_id'], ['external_identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['external_resource_id'], ['external_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_identity_id', 'external_resource_id', 'permission', name='uq_external_permission')
    )
    op.create_index(op.f('ix_external_permissions_external_identity_id'), 'external_permissions', ['external_identity_id'], unique=False)
    op.create_index(op.f('ix_external_permissions_external_resource_id'), 'external_permissions', ['external_resource_id'], unique=False)
    op.create_index(op.f('ix_external_permissions_id'), 'external_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_permissions_id'), table_name='external_permissions')
    op.drop_index(op.f('ix_external_permissions_external_resource_id'), table_name='external_permissions')
    op.drop_index(op.f('ix_external_permissions_external_identity_id'), table_name='external_permissions')
    op.drop_table('external_permissions')
    op.drop_index(op.f('ix_external_identities_user_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_external_user_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_connector_name'), table_name='external_identities')
    op.drop_table('external_identities')
    op.drop_index(op.f('ix_external_resources_id'), table_name='external_resources')
    op.drop_index(op.f('ix_external_resources_external_resource_id'), table_name='external_resources')
    op.drop_index(op.f('ix_external_resources_connector_name'), table_name='external_resources')
    op.drop_table('external_resources')
    # ### end Alembic commands ###
