"""add team views and external permissions

Revision ID: e1caa5284855
Revises: 34e8f62e0154
Create Date: 2026-08-19 00:58:45.504068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1caa5284855'
down_revision: Union[str, Sequence[str], None] = '34e8f62e0154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='inactive', nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('credential_ref', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_connector_type'), 'connectors', ['connector_type'], unique=False)
    op.create_index(op.f('ix_connectors_id'), 'connectors', ['id'], unique=False)
    op.create_index(op.f('ix_connectors_status'), 'connectors', ['status'], unique=False)
    op.create_index(op.f('ix_connectors_workspace_id'), 'connectors', ['workspace_id'], unique=False)
    op.create_table('team_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('view_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_views_id'), 'team_views', ['id'], unique=False)
    op.create_index(op.f('ix_team_views_team'), 'team_views', ['team'], unique=False)
    op.create_index(op.f('ix_team_views_view_type'), 'team_views', ['view_type'], unique=False)
    op.create_index(op.f('ix_team_views_workspace_id'), 'team_views', ['workspace_id'], unique=False)
    op.add_column('deals', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('deals', sa.Column('probability', sa.Float(), nullable=True))
    op.add_column('deals', sa.Column('expected_close_date', sa.DateTime(), nullable=True))
    op.add_column('deals', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_deals_created_by'), table_name='deals')
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_stage'), 'deals', ['stage'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_index(op.f('ix_deals_title'), 'deals', ['title'], unique=False)
    op.drop_constraint(op.f('deals_person_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_workspace_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_project_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_created_by_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_company_id_fkey'), 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'users', ['person_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'deals', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deals', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'deals', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_column('deals', 'name')
    op.drop_column('deals', 'created_by')
    op.drop_column('deals', 'expected_close_at')
    op.add_column('external_identities', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.add_column('external_identities', sa.Column('connector_id', sa.Integer(), nullable=True))
    op.add_column('external_identities', sa.Column('external_id', sa.String(length=255), nullable=False))
    op.add_column('external_identities', sa.Column('external_name', sa.String(length=255), nullable=True))
    op.add_column('external_identities', sa.Column('provider', sa.String(length=100), nullable=False))
    op.add_column('external_identities', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.alter_column('external_identities', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_external_identities_connector_name'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_external_user_id'), table_name='external_identities')
    op.drop_constraint(op.f('uq_external_identity_connector_user'), 'external_identities', type_='unique')
    op.create_index(op.f('ix_external_identities_connector_id'), 'external_identities', ['connector_id'], unique=False)
    op.create_index(op.f('ix_external_identities_external_email'), 'external_identities', ['external_email'], unique=False)
    op.create_index(op.f('ix_external_identities_external_id'), 'external_identities', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_identities_provider'), 'external_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_external_identities_workspace_id'), 'external_identities', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('external_identities_user_id_fkey'), 'external_identities', type_='foreignkey')
    op.create_foreign_key(None, 'external_identities', 'connectors', ['connector_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'external_identities', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'external_identities', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('external_identities', 'connector_name')
    op.drop_column('external_identities', 'external_user_id')
    op.drop_column('external_identities', 'external_username')
    op.add_column('external_permissions', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.add_column('external_permissions', sa.Column('connector_id', sa.Integer(), nullable=True))
    op.add_column('external_permissions', sa.Column('granted', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('external_permissions', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('external_permissions', sa.Column('synced_at', sa.DateTime(), nullable=False))
    op.alter_column('external_permissions', 'permission',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('external_permissions', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('uq_external_permission'), 'external_permissions', type_='unique')
    op.create_index(op.f('ix_external_permissions_connector_id'), 'external_permissions', ['connector_id'], unique=False)
    op.create_index(op.f('ix_external_permissions_workspace_id'), 'external_permissions', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'external_permissions', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'external_permissions', 'connectors', ['connector_id'], ['id'], ondelete='SET NULL')
    op.drop_column('external_permissions', 'inherited')
    op.drop_column('external_permissions', 'is_active')
    op.add_column('external_resources', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.add_column('external_resources', sa.Column('connector_id', sa.Integer(), nullable=True))
    op.add_column('external_resources', sa.Column('external_id', sa.String(length=500), nullable=False))
    op.add_column('external_resources', sa.Column('name', sa.String(length=500), nullable=True))
    op.add_column('external_resources', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('external_resources', sa.Column('provider', sa.String(length=100), nullable=False))
    op.add_column('external_resources', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_external_resources_connector_name'), table_name='external_resources')
    op.drop_index(op.f('ix_external_resources_external_resource_id'), table_name='external_resources')
    op.drop_constraint(op.f('uq_external_resource_connector_resource'), 'external_resources', type_='unique')
    op.create_index(op.f('ix_external_resources_connector_id'), 'external_resources', ['connector_id'], unique=False)
    op.create_index(op.f('ix_external_resources_external_id'), 'external_resources', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_resources_provider'), 'external_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_external_resources_resource_type'), 'external_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_external_resources_workspace_id'), 'external_resources', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'external_resources', 'connectors', ['connector_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'external_resources', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('external_resources', 'last_synced_at')
    op.drop_column('external_resources', 'connector_name')
    op.drop_column('external_resources', 'parent_resource_id')
    op.drop_column('external_resources', 'resource_name')
    op.drop_column('external_resources', 'external_resource_id')
    op.drop_column('external_resources', 'resource_url')
    op.drop_column('meeting_transcripts', 'created_at')
    op.drop_column('meeting_transcripts', 'text')
    op.drop_column('meeting_transcripts', 'end_time_seconds')
    op.drop_column('meeting_transcripts', 'sequence_number')
    op.add_column('tickets', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('tickets', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_tickets_created_by'), table_name='tickets')
    op.create_index(op.f('ix_tickets_category'), 'tickets', ['category'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    op.drop_constraint(op.f('tickets_person_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_assigned_to_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_created_by_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_company_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_project_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_workspace_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['person_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_column('tickets', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_workspace_id_fkey'), 'tickets', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('tickets_project_id_fkey'), 'tickets', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('tickets_company_id_fkey'), 'tickets', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(op.f('tickets_created_by_fkey'), 'tickets', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('tickets_assigned_to_fkey'), 'tickets', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('tickets_person_id_fkey'), 'tickets', 'people', ['person_id'], ['id'])
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category'), table_name='tickets')
    op.create_index(op.f('ix_tickets_created_by'), 'tickets', ['created_by'], unique=False)
    op.drop_column('tickets', 'resolved_at')
    op.drop_column('tickets', 'metadata_json')
    op.add_column('meeting_transcripts', sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('meeting_transcripts', sa.Column('end_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('meeting_transcripts', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('meeting_transcripts', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('external_resources', sa.Column('resource_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('external_resources', sa.Column('external_resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('external_resources', sa.Column('resource_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('external_resources', sa.Column('parent_resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('external_resources', sa.Column('connector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('external_resources', sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'external_resources', type_='foreignkey')
    op.drop_constraint(None, 'external_resources', type_='foreignkey')
    op.drop_index(op.f('ix_external_resources_workspace_id'), table_name='external_resources')
    op.drop_index(op.f('ix_external_resources_resource_type'), table_name='external_resources')
    op.drop_index(op.f('ix_external_resources_provider'), table_name='external_resources')
    op.drop_index(op.f('ix_external_resources_external_id'), table_name='external_resources')
    op.drop_index(op.f('ix_external_resources_connector_id'), table_name='external_resources')
    op.create_unique_constraint(op.f('uq_external_resource_connector_resource'), 'external_resources', ['connector_name', 'external_resource_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_external_resources_external_resource_id'), 'external_resources', ['external_resource_id'], unique=False)
    op.create_index(op.f('ix_external_resources_connector_name'), 'external_resources', ['connector_name'], unique=False)
    op.drop_column('external_resources', 'metadata_json')
    op.drop_column('external_resources', 'provider')
    op.drop_column('external_resources', 'url')
    op.drop_column('external_resources', 'name')
    op.drop_column('external_resources', 'external_id')
    op.drop_column('external_resources', 'connector_id')
    op.drop_column('external_resources', 'workspace_id')
    op.add_column('external_permissions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('external_permissions', sa.Column('inherited', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'external_permissions', type_='foreignkey')
    op.drop_constraint(None, 'external_permissions', type_='foreignkey')
    op.drop_index(op.f('ix_external_permissions_workspace_id'), table_name='external_permissions')
    op.drop_index(op.f('ix_external_permissions_connector_id'), table_name='external_permissions')
    op.create_unique_constraint(op.f('uq_external_permission'), 'external_permissions', ['external_identity_id', 'external_resource_id', 'permission'], postgresql_nulls_not_distinct=False)
    op.alter_column('external_permissions', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('external_permissions', 'permission',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('external_permissions', 'synced_at')
    op.drop_column('external_permissions', 'metadata_json')
    op.drop_column('external_permissions', 'granted')
    op.drop_column('external_permissions', 'connector_id')
    op.drop_column('external_permissions', 'workspace_id')
    op.add_column('external_identities', sa.Column('external_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('external_identities', sa.Column('external_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('external_identities', sa.Column('connector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'external_identities', type_='foreignkey')
    op.drop_constraint(None, 'external_identities', type_='foreignkey')
    op.drop_constraint(None, 'external_identities', type_='foreignkey')
    op.create_foreign_key(op.f('external_identities_user_id_fkey'), 'external_identities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_external_identities_workspace_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_provider'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_external_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_external_email'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_connector_id'), table_name='external_identities')
    op.create_unique_constraint(op.f('uq_external_identity_connector_user'), 'external_identities', ['connector_name', 'external_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_external_identities_external_user_id'), 'external_identities', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_external_identities_connector_name'), 'external_identities', ['connector_name'], unique=False)
    op.alter_column('external_identities', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('external_identities', 'metadata_json')
    op.drop_column('external_identities', 'provider')
    op.drop_column('external_identities', 'external_name')
    op.drop_column('external_identities', 'external_id')
    op.drop_column('external_identities', 'connector_id')
    op.drop_column('external_identities', 'workspace_id')
    op.add_column('deals', sa.Column('expected_close_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key(op.f('deals_company_id_fkey'), 'deals', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(op.f('deals_created_by_fkey'), 'deals', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('deals_project_id_fkey'), 'deals', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('deals_workspace_id_fkey'), 'deals', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('deals_person_id_fkey'), 'deals', 'people', ['person_id'], ['id'])
    op.drop_index(op.f('ix_deals_title'), table_name='deals')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.create_index(op.f('ix_deals_created_by'), 'deals', ['created_by'], unique=False)
    op.drop_column('deals', 'metadata_json')
    op.drop_column('deals', 'expected_close_date')
    op.drop_column('deals', 'probability')
    op.drop_column('deals', 'title')
    op.drop_index(op.f('ix_team_views_workspace_id'), table_name='team_views')
    op.drop_index(op.f('ix_team_views_view_type'), table_name='team_views')
    op.drop_index(op.f('ix_team_views_team'), table_name='team_views')
    op.drop_index(op.f('ix_team_views_id'), table_name='team_views')
    op.drop_table('team_views')
    op.drop_index(op.f('ix_connectors_workspace_id'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_status'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_id'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_connector_type'), table_name='connectors')
    op.drop_table('connectors')
    # ### end Alembic commands ###
